variables:
    GIT_DEPTH: "1"

stages:
    - develop_build
    - prepare_develop_debs

develop_build:
    tags:
        - Runner-Stretch
    stage: develop_build
    script:
        - dpkg-buildpackage -us -uc -b
        - mv ../*.deb .
        - mv ../*.buildinfo .
        - mv ../*.changes .
    artifacts:
        name: "${CI_PROJECT_NAME}"
        paths:
        - ./*.deb
        - ./*.buildinfo
        - ./*.changes

prepare_develop_debs:
    tags:
        - Runner-Stretch
    stage: prepare_develop_debs
    only:
      refs:
        - stretch/master
    dependencies:
        - develop_build
    when: manual
    script:
        - mkdir -p /cache/stretch/develop/
        - cp *.deb /cache/stretch/develop/
        - ls /cache/stretch/develop/
