variables:
    GIT_DEPTH: "1"

stages:
    - mil-internal-release_build
    - prepare_mil-internal-release_debs

mil-internal-release_build:
    tags:
        - Runner-Stretch
    stage: mil-internal-release_build
    script:
        - dpkg-buildpackage -us -uc -b
        - mv ../*.deb .
        - mv ../*.buildinfo .
        - mv ../*.changes .
    artifacts:
        name: "${CI_PROJECT_NAME}"
        paths:
        - ./*.deb
        - ./*.buildinfo
        - ./*.changes

prepare_mil-internal-release_debs:
    tags:
        - Runner-Stretch
    stage: prepare_mil-internal-release_debs
    only:
      refs:
        - stretch/master
    dependencies:
        - mil-internal-release_build
    when: manual
    script:
        - mkdir -p /cache/stretch/mil-internal-release/
        - cp *.deb /cache/stretch/mil-internal-release/
        - ls /cache/stretch/mil-internal-release/
